name: CI
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: ci # will run `yarn install` command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # if needed
      - name: Build production bundle
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build # will run `yarn build` command

      - name: Test the app
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: test # will run `yarn test` command
