name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - "18"
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn run lint
      - run: yarn build
      - run: yarn test

